// const sum = (a, b) => {
//   if (a && b) {
//     return a + b;
//   }
//   throw new Error("Invalid Argument");
// };

// try {
//   console.log(sum(10), "sum");
// } catch (err) {
//   console.log("err");
//   //   console.log(err);
// }

// // console.log(sum(10), "sum");

// console.log("This works!!");
